=== AldoRicchieroFilho/dev-site/site/src/main/resources/folder.dtd
<!ELEMENT folder (toc?)>
<!ATTLIST folder
        displayName CDATA #IMPLIED
        href CDATA #IMPLIED
        title CDATA #IMPLIED
        description CDATA #IMPLIED
        style CDATA #IMPLIED
        logo CDATA #IMPLIED
>

<!ELEMENT toc (
        (entries?,excludes?) |
        (excludes?,entries?)
)>

<!ELEMENT excludes (exclude*)>
<!ELEMENT exclude (#PCDATA)>

<!ELEMENT entries (entry*)>
<!ELEMENT entry (entry*)>
<!ATTLIST entry
        name CDATA #REQUIRED
        displayName CDATA #IMPLIED
        title CDATA #IMPLIED
        description CDATA #IMPLIED
>

=== AldoRicchieroFilho/dev-site/site/src/main/markdown/gwtp/communication/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE folder SYSTEM "folder.dtd">
<folder title="Communication" displayName="Communication">
    <toc>
        <entries>
            <entry name="index" title="Rest Dispatch" displayName="Rest Dispatch"
                    description="REST Dispatch allows your client code to send HTTP requests in a REST fashion to any server."/>
            <entry name="RPC-Dispatch" title="RPC-Dispatch" displayName="RPC-Dispatch"
                    description="Remote Procedure Call Dispatcher is a client server communication protocol. It serializes and deserializes the objects being sent over the wire."/>
            <entry name="action-validators" title="Action Validators" displayName="Action Validators"
                    description="GWTP makes it possible to link each of your ActionHandlers with a server-side ActionValidator that determines whether or not the current client can execute the action."/>
            <entry name="Client-Action-Handlers" title="Client Action Handlers" displayName="Client Action Handlers"
                    description="Client action handlers or rpc-dispatch."/>
            <entry name="CSRF-Protection" title="CSRF Protection" displayName="CSRF Protection"
                    description="GWTP comes with built-in protection against CSRF attacks."/>
        </entries>
    </toc>
</folder>

=== AldoRicchieroFilho/dev-site/site/src/main/markdown/gwtp_v2/resources/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE folder SYSTEM "folder.dtd">
<folder>
    <toc>
        <entries>
            <entry name="" displayName="Community Support"/>
            <entry name="#plugins" displayName="IDE Plugins"/>
            <entry name="#samples" displayName="Samples"/>
            <entry name="#release-notes" displayName="Release notes"/>
            <entry name="#migration-guides" displayName="Migration Guides">
                <entry name="Migrating-from-07-to-10" title="Migrating from v. 0.7 to 1.0"
                        displayName="Migrating from v. 0.7 to 1.0"/>
                <entry name="Migrating-from-11-to-12" title="Migrating from v. 1.1 to 1.2"
                        displayName="Migrating from v. 1.1 to 1.2"/>
                <entry name="Migrating-from-13-to-14" title="Migrating from v. 1.3 to 1.4"
                        displayName="Migrating from v. 1.3 to 1.4"/>
            </entry>
        </entries>
    </toc>
</folder>

=== AldoRicchieroFilho/dev-site/site/src/main/markdown/gwtp/advanced/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE folder SYSTEM "folder.dtd">
<folder title="Advanced Features" displayName="Advanced Features">
    <toc>
        <entries>
            <entry name="index" title="Form Factors" displayName="Form Factors"/>
            <entry name="Phonegap-support" title="Phonegap Support" displayName="Phonegap Support"/>
            <entry name="crawler-support" title="Crawler Support" displayName="Crawler Support"/>
            <entry name="Custom-Proxy-Class" title="Custom Proxy Class" displayName="Custom Proxy Class"/>
            <entry name="Google-Universal-Analytics" title="Google Universal Analytics" displayName="Google Universal Analytics"/>
            <entry name="Merge-Locale" title="Merge Locale" displayName="Merge Locale"/>
        </entries>
    </toc>
</folder>

=== AldoRicchieroFilho/dev-site/site/src/main/markdown/gwtp/core/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE folder SYSTEM "folder.dtd">
<folder title="Core (MVP)" displayName="Core (MVP)" href="presenters/">
    <toc>
        <entries>
            <entry name="presenters/" displayName="Presenters"
                    description="Base, Visual, Bottom-Top communication and more."/>
            <entry name="slots/" displayName="Link Presenters (Slots)"
                    description="Presenters in GWTP have a concept of slots. Slots are basically placeholders where the child presenters are put and associated to their parent presenter."/>
            <entry name="navigation/" displayName="Navigation"
                    description="Linking places to a token, revealing places, token formats and more."/>
            <entry name="security/" displayName="Security"
                    description="Gatekeepers are used to protect places from unauthorized access."/>
            <entry name="events/" displayName="Events"
                    description="Writing events based on the GWT way."/>
            <entry name="optimizations" displayName="Optimizations"
                    description="Code Splitting allows the JavaScript code to be split into multiple files that will be loaded depending on the application section being used."/>
        </entries>
    </toc>
</folder>

=== AldoRicchieroFilho/dev-site/site/src/main/markdown/gwtp/core/presenters/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE folder SYSTEM "folder.dtd">
<folder title="Presenters" description="Presenters">
    <toc>
        <entries>
            <entry name="index" title="The base: PresenterWidget"
                    displayName="The base: PresenterWidget"
                    description="GWTP's PresenterWidget is a great tool that leverages the power of regular GWT Widgets."/>

            <entry name="view" title="The visual: View &amp; ViewImpl"
                    displayName="The visual: View &amp; ViewImpl"
                    description="Its purpose is to separate the application logic from the display logic."/>

            <entry name="view-with-ui-handlers" title="Bottom-Top Communication: UiHandlers &amp; ViewWithUiHandlers"
                    displayName="Bottom-Top Communication: UiHandlers &amp; ViewWithUiHandlers"
                    description="The way to link a view event to a Presenter is with the Bottom-Top Communication pattern."/>

            <entry name="creating-places" title="Creating places: Presenter and Proxy"
                    displayName="Creating places: Presenter and Proxy"
                    description="A Place represents a particular 'bookmark' or location inside the application."/>

            <entry name="lifecycle" title="Lifecycle"
                    displayName="Lifecycle"
                    description="A PresenterWidget has multiple phases in its lifecycle. GWTP gives the user access to many handles to execute code during each phase."/>

            <entry name="popups" title="Popups"
                    displayName="Popups"
                    description="A popup presenter is a standard presenter with a view that extends PopupView."/>

            <entry name="gin-bindings" title="Bindings with GIN"
                    displayName="Bindings with GIN"
                    description="GWTP uses dependency injection as a foundation of its architecture. It allows to have a maintainable application and loosely coupled components."/>
        </entries>
    </toc>
</folder>

=== AldoRicchieroFilho/dev-site/site/src/main/markdown/gwtp/core/navigation/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE folder SYSTEM "folder.dtd">
<folder title="Navigation" displayName="Navigation">
    <toc>
        <entries>
            <entry name="index" title="Linking Places to a Token" displayName="Linking Places to a Token"
                    description="Some presenters can be associated to a specific URL. GWTP makes it possible by managing the hash section of the URL."/>
            <entry name="reveal-places" title="Revealing Places" displayName="Revealing Places"
                    description="Display the presenter associated with the requested token and trigger the lifecycle methods on that presenter."/>
            <entry name="token-formats" title="Token Formats" displayName="Token Formats"
                    description="Default, Crawlable and Route Token Formatter."/>
            <entry name="navigation-confirmation" title="Navigation Confirmation"
                    displayName="Navigation Confirmation"
                    description="GWTP offers a built-in mechanism to display a confirmation dialog when the user tries to leave a page without saving its changes."/>
            <entry name="manual-reveal" title="Manual Reveal (Presenters)" displayName="Manual Reveal (Presenters)"
                    description="Manual reveal gives you greater control over the precise moment at which a presenter is revealed."/>
        </entries>
    </toc>
</folder>

=== AldoRicchieroFilho/dev-site/site/src/main/markdown/gwtp/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE folder SYSTEM "folder.dtd">
<folder title="GWTP" displayName="GWTP" style="gwtp">
    <toc>
        <entries>
            <entry name="index" displayName="Overview"/>
            <entry name="tutorials/" displayName="Beginner's Tutorial"/>
            <entry name="get-started/" displayName="Get Started"/>
            <entry name="core/" displayName="Core (MVP)"/>
            <entry name="advanced/" displayName="Advanced Features"/>
            <entry name="communication/" displayName="Communication"/>
            <entry name="tools/" displayName="Tools and Patterns"/>
            <entry name="resources/" displayName="Resources"/>
            <entry name="contributing/" displayName="Contributing"/>
            <entry name="License" displayName="License"/>
        </entries>
    </toc>
</folder>

=== AldoRicchieroFilho/dev-site/site/src/main/markdown/gwtp/tools/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE folder SYSTEM "folder.dtd">
<folder title="Tools and Patterns" displayName="Tools and Patterns">
    <toc>
        <entries>
            <entry name="index" title="Resources" displayName="Resources"
                    description="Bbootstrapping and using resources. This goes over resource types Messages, Constants, CSS and Images."/>
            <entry name="Observer" title="Observer" displayName="Observer"
                    description="Grouped Events Observing."/>
            <entry name="Website-Embedding" title="Website Embedding" displayName="Website Embedding"
                    description="Embedding GWTP application into a website."/>
            <entry name="Boilerplate-Generation" title="Boilerplate Generation" displayName="Boilerplate Generation"
                    description="GWTP provides annotation processors that reduce the effort of creating classes that primarily consist of boilerplate code."/>
            <entry name="Unit-Testing-Cookbook" title="Unit Testing Cookbook" displayName="Unit Testing Cookbook"
                    description="How to write unit tests for your GWTP Presenters, using the power of Jukito."/>
        </entries>
    </toc>
</folder>
